<?php
/**
 * ChangeDomainNameserversRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Model;

use \ArrayAccess;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * ChangeDomainNameserversRequest Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ChangeDomainNameserversRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'changeDomainNameservers_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'cname' => 'string',
        'dns_servers_opt' => 'string',
        'ns' => 'string[]',
        'ns1' => 'string',
        'ns1_ipv4' => 'string',
        'ns1_ipv6' => 'string',
        'ns2' => 'string',
        'ns2_ipv4' => 'string',
        'ns2_ipv6' => 'string',
        'ns3' => 'string',
        'ns3_ipv4' => 'string',
        'ns3_ipv6' => 'string',
        'ns4' => 'string',
        'ns4_ipv4' => 'string',
        'ns4_ipv6' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'cname' => null,
        'dns_servers_opt' => null,
        'ns' => null,
        'ns1' => null,
        'ns1_ipv4' => null,
        'ns1_ipv6' => null,
        'ns2' => null,
        'ns2_ipv4' => null,
        'ns2_ipv6' => null,
        'ns3' => null,
        'ns3_ipv4' => null,
        'ns3_ipv6' => null,
        'ns4' => null,
        'ns4_ipv4' => null,
        'ns4_ipv6' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'cname' => false,
        'dns_servers_opt' => false,
        'ns' => false,
        'ns1' => false,
        'ns1_ipv4' => false,
        'ns1_ipv6' => false,
        'ns2' => false,
        'ns2_ipv4' => false,
        'ns2_ipv6' => false,
        'ns3' => false,
        'ns3_ipv4' => false,
        'ns3_ipv6' => false,
        'ns4' => false,
        'ns4_ipv4' => false,
        'ns4_ipv6' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cname' => 'cname',
        'dns_servers_opt' => 'dns_servers_opt',
        'ns' => 'ns',
        'ns1' => 'ns1',
        'ns1_ipv4' => 'ns1_ipv4',
        'ns1_ipv6' => 'ns1_ipv6',
        'ns2' => 'ns2',
        'ns2_ipv4' => 'ns2_ipv4',
        'ns2_ipv6' => 'ns2_ipv6',
        'ns3' => 'ns3',
        'ns3_ipv4' => 'ns3_ipv4',
        'ns3_ipv6' => 'ns3_ipv6',
        'ns4' => 'ns4',
        'ns4_ipv4' => 'ns4_ipv4',
        'ns4_ipv6' => 'ns4_ipv6'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cname' => 'setCname',
        'dns_servers_opt' => 'setDnsServersOpt',
        'ns' => 'setNs',
        'ns1' => 'setNs1',
        'ns1_ipv4' => 'setNs1Ipv4',
        'ns1_ipv6' => 'setNs1Ipv6',
        'ns2' => 'setNs2',
        'ns2_ipv4' => 'setNs2Ipv4',
        'ns2_ipv6' => 'setNs2Ipv6',
        'ns3' => 'setNs3',
        'ns3_ipv4' => 'setNs3Ipv4',
        'ns3_ipv6' => 'setNs3Ipv6',
        'ns4' => 'setNs4',
        'ns4_ipv4' => 'setNs4Ipv4',
        'ns4_ipv6' => 'setNs4Ipv6'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cname' => 'getCname',
        'dns_servers_opt' => 'getDnsServersOpt',
        'ns' => 'getNs',
        'ns1' => 'getNs1',
        'ns1_ipv4' => 'getNs1Ipv4',
        'ns1_ipv6' => 'getNs1Ipv6',
        'ns2' => 'getNs2',
        'ns2_ipv4' => 'getNs2Ipv4',
        'ns2_ipv6' => 'getNs2Ipv6',
        'ns3' => 'getNs3',
        'ns3_ipv4' => 'getNs3Ipv4',
        'ns3_ipv6' => 'getNs3Ipv6',
        'ns4' => 'getNs4',
        'ns4_ipv4' => 'getNs4Ipv4',
        'ns4_ipv6' => 'getNs4Ipv6'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cname', $data ?? [], null);
        $this->setIfExists('dns_servers_opt', $data ?? [], null);
        $this->setIfExists('ns', $data ?? [], null);
        $this->setIfExists('ns1', $data ?? [], null);
        $this->setIfExists('ns1_ipv4', $data ?? [], null);
        $this->setIfExists('ns1_ipv6', $data ?? [], null);
        $this->setIfExists('ns2', $data ?? [], null);
        $this->setIfExists('ns2_ipv4', $data ?? [], null);
        $this->setIfExists('ns2_ipv6', $data ?? [], null);
        $this->setIfExists('ns3', $data ?? [], null);
        $this->setIfExists('ns3_ipv4', $data ?? [], null);
        $this->setIfExists('ns3_ipv6', $data ?? [], null);
        $this->setIfExists('ns4', $data ?? [], null);
        $this->setIfExists('ns4_ipv4', $data ?? [], null);
        $this->setIfExists('ns4_ipv6', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cname
     *
     * @return string|null
     */
    public function getCname()
    {
        return $this->container['cname'];
    }

    /**
     * Sets cname
     *
     * @param string|null $cname cname
     *
     * @return self
     */
    public function setCname($cname)
    {
        if (is_null($cname)) {
            throw new \InvalidArgumentException('non-nullable cname cannot be null');
        }
        $this->container['cname'] = $cname;

        return $this;
    }

    /**
     * Gets dns_servers_opt
     *
     * @return string|null
     */
    public function getDnsServersOpt()
    {
        return $this->container['dns_servers_opt'];
    }

    /**
     * Sets dns_servers_opt
     *
     * @param string|null $dns_servers_opt dns_servers_opt
     *
     * @return self
     */
    public function setDnsServersOpt($dns_servers_opt)
    {
        if (is_null($dns_servers_opt)) {
            throw new \InvalidArgumentException('non-nullable dns_servers_opt cannot be null');
        }
        $this->container['dns_servers_opt'] = $dns_servers_opt;

        return $this;
    }

    /**
     * Gets ns
     *
     * @return string[]|null
     */
    public function getNs()
    {
        return $this->container['ns'];
    }

    /**
     * Sets ns
     *
     * @param string[]|null $ns ns
     *
     * @return self
     */
    public function setNs($ns)
    {
        if (is_null($ns)) {
            throw new \InvalidArgumentException('non-nullable ns cannot be null');
        }
        $this->container['ns'] = $ns;

        return $this;
    }

    /**
     * Gets ns1
     *
     * @return string|null
     */
    public function getNs1()
    {
        return $this->container['ns1'];
    }

    /**
     * Sets ns1
     *
     * @param string|null $ns1 ns1
     *
     * @return self
     */
    public function setNs1($ns1)
    {
        if (is_null($ns1)) {
            throw new \InvalidArgumentException('non-nullable ns1 cannot be null');
        }
        $this->container['ns1'] = $ns1;

        return $this;
    }

    /**
     * Gets ns1_ipv4
     *
     * @return string|null
     */
    public function getNs1Ipv4()
    {
        return $this->container['ns1_ipv4'];
    }

    /**
     * Sets ns1_ipv4
     *
     * @param string|null $ns1_ipv4 ns1_ipv4
     *
     * @return self
     */
    public function setNs1Ipv4($ns1_ipv4)
    {
        if (is_null($ns1_ipv4)) {
            throw new \InvalidArgumentException('non-nullable ns1_ipv4 cannot be null');
        }
        $this->container['ns1_ipv4'] = $ns1_ipv4;

        return $this;
    }

    /**
     * Gets ns1_ipv6
     *
     * @return string|null
     */
    public function getNs1Ipv6()
    {
        return $this->container['ns1_ipv6'];
    }

    /**
     * Sets ns1_ipv6
     *
     * @param string|null $ns1_ipv6 ns1_ipv6
     *
     * @return self
     */
    public function setNs1Ipv6($ns1_ipv6)
    {
        if (is_null($ns1_ipv6)) {
            throw new \InvalidArgumentException('non-nullable ns1_ipv6 cannot be null');
        }
        $this->container['ns1_ipv6'] = $ns1_ipv6;

        return $this;
    }

    /**
     * Gets ns2
     *
     * @return string|null
     */
    public function getNs2()
    {
        return $this->container['ns2'];
    }

    /**
     * Sets ns2
     *
     * @param string|null $ns2 ns2
     *
     * @return self
     */
    public function setNs2($ns2)
    {
        if (is_null($ns2)) {
            throw new \InvalidArgumentException('non-nullable ns2 cannot be null');
        }
        $this->container['ns2'] = $ns2;

        return $this;
    }

    /**
     * Gets ns2_ipv4
     *
     * @return string|null
     */
    public function getNs2Ipv4()
    {
        return $this->container['ns2_ipv4'];
    }

    /**
     * Sets ns2_ipv4
     *
     * @param string|null $ns2_ipv4 ns2_ipv4
     *
     * @return self
     */
    public function setNs2Ipv4($ns2_ipv4)
    {
        if (is_null($ns2_ipv4)) {
            throw new \InvalidArgumentException('non-nullable ns2_ipv4 cannot be null');
        }
        $this->container['ns2_ipv4'] = $ns2_ipv4;

        return $this;
    }

    /**
     * Gets ns2_ipv6
     *
     * @return string|null
     */
    public function getNs2Ipv6()
    {
        return $this->container['ns2_ipv6'];
    }

    /**
     * Sets ns2_ipv6
     *
     * @param string|null $ns2_ipv6 ns2_ipv6
     *
     * @return self
     */
    public function setNs2Ipv6($ns2_ipv6)
    {
        if (is_null($ns2_ipv6)) {
            throw new \InvalidArgumentException('non-nullable ns2_ipv6 cannot be null');
        }
        $this->container['ns2_ipv6'] = $ns2_ipv6;

        return $this;
    }

    /**
     * Gets ns3
     *
     * @return string|null
     */
    public function getNs3()
    {
        return $this->container['ns3'];
    }

    /**
     * Sets ns3
     *
     * @param string|null $ns3 ns3
     *
     * @return self
     */
    public function setNs3($ns3)
    {
        if (is_null($ns3)) {
            throw new \InvalidArgumentException('non-nullable ns3 cannot be null');
        }
        $this->container['ns3'] = $ns3;

        return $this;
    }

    /**
     * Gets ns3_ipv4
     *
     * @return string|null
     */
    public function getNs3Ipv4()
    {
        return $this->container['ns3_ipv4'];
    }

    /**
     * Sets ns3_ipv4
     *
     * @param string|null $ns3_ipv4 ns3_ipv4
     *
     * @return self
     */
    public function setNs3Ipv4($ns3_ipv4)
    {
        if (is_null($ns3_ipv4)) {
            throw new \InvalidArgumentException('non-nullable ns3_ipv4 cannot be null');
        }
        $this->container['ns3_ipv4'] = $ns3_ipv4;

        return $this;
    }

    /**
     * Gets ns3_ipv6
     *
     * @return string|null
     */
    public function getNs3Ipv6()
    {
        return $this->container['ns3_ipv6'];
    }

    /**
     * Sets ns3_ipv6
     *
     * @param string|null $ns3_ipv6 ns3_ipv6
     *
     * @return self
     */
    public function setNs3Ipv6($ns3_ipv6)
    {
        if (is_null($ns3_ipv6)) {
            throw new \InvalidArgumentException('non-nullable ns3_ipv6 cannot be null');
        }
        $this->container['ns3_ipv6'] = $ns3_ipv6;

        return $this;
    }

    /**
     * Gets ns4
     *
     * @return string|null
     */
    public function getNs4()
    {
        return $this->container['ns4'];
    }

    /**
     * Sets ns4
     *
     * @param string|null $ns4 ns4
     *
     * @return self
     */
    public function setNs4($ns4)
    {
        if (is_null($ns4)) {
            throw new \InvalidArgumentException('non-nullable ns4 cannot be null');
        }
        $this->container['ns4'] = $ns4;

        return $this;
    }

    /**
     * Gets ns4_ipv4
     *
     * @return string|null
     */
    public function getNs4Ipv4()
    {
        return $this->container['ns4_ipv4'];
    }

    /**
     * Sets ns4_ipv4
     *
     * @param string|null $ns4_ipv4 ns4_ipv4
     *
     * @return self
     */
    public function setNs4Ipv4($ns4_ipv4)
    {
        if (is_null($ns4_ipv4)) {
            throw new \InvalidArgumentException('non-nullable ns4_ipv4 cannot be null');
        }
        $this->container['ns4_ipv4'] = $ns4_ipv4;

        return $this;
    }

    /**
     * Gets ns4_ipv6
     *
     * @return string|null
     */
    public function getNs4Ipv6()
    {
        return $this->container['ns4_ipv6'];
    }

    /**
     * Sets ns4_ipv6
     *
     * @param string|null $ns4_ipv6 ns4_ipv6
     *
     * @return self
     */
    public function setNs4Ipv6($ns4_ipv6)
    {
        if (is_null($ns4_ipv6)) {
            throw new \InvalidArgumentException('non-nullable ns4_ipv6 cannot be null');
        }
        $this->container['ns4_ipv6'] = $ns4_ipv6;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


