<?php
/**
 * CreateVehicleEventRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Model;

use \ArrayAccess;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * CreateVehicleEventRequest Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateVehicleEventRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'createVehicleEvent_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'event_type' => 'string',
        'datetime_local' => 'string',
        'timezone' => 'string',
        'location' => '\Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestLocation',
        'vehicle_id' => 'string',
        'purpose' => 'string',
        'notes' => 'string',
        'odometer' => 'int',
        'money' => '\Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestMoney',
        'fueling' => '\Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestFueling'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'event_type' => null,
        'datetime_local' => null,
        'timezone' => null,
        'location' => null,
        'vehicle_id' => null,
        'purpose' => null,
        'notes' => null,
        'odometer' => null,
        'money' => null,
        'fueling' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'event_type' => false,
        'datetime_local' => false,
        'timezone' => false,
        'location' => false,
        'vehicle_id' => false,
        'purpose' => false,
        'notes' => false,
        'odometer' => false,
        'money' => false,
        'fueling' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'event_type' => 'eventType',
        'datetime_local' => 'datetimeLocal',
        'timezone' => 'timezone',
        'location' => 'location',
        'vehicle_id' => 'vehicleId',
        'purpose' => 'purpose',
        'notes' => 'notes',
        'odometer' => 'odometer',
        'money' => 'money',
        'fueling' => 'fueling'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'event_type' => 'setEventType',
        'datetime_local' => 'setDatetimeLocal',
        'timezone' => 'setTimezone',
        'location' => 'setLocation',
        'vehicle_id' => 'setVehicleId',
        'purpose' => 'setPurpose',
        'notes' => 'setNotes',
        'odometer' => 'setOdometer',
        'money' => 'setMoney',
        'fueling' => 'setFueling'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'event_type' => 'getEventType',
        'datetime_local' => 'getDatetimeLocal',
        'timezone' => 'getTimezone',
        'location' => 'getLocation',
        'vehicle_id' => 'getVehicleId',
        'purpose' => 'getPurpose',
        'notes' => 'getNotes',
        'odometer' => 'getOdometer',
        'money' => 'getMoney',
        'fueling' => 'getFueling'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('datetime_local', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('vehicle_id', $data ?? [], null);
        $this->setIfExists('purpose', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('odometer', $data ?? [], null);
        $this->setIfExists('money', $data ?? [], null);
        $this->setIfExists('fueling', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['event_type'] === null) {
            $invalidProperties[] = "'event_type' can't be null";
        }
        if ($this->container['datetime_local'] === null) {
            $invalidProperties[] = "'datetime_local' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['location'] === null) {
            $invalidProperties[] = "'location' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event_type
     *
     * @return string
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string $event_type event_type
     *
     * @return self
     */
    public function setEventType($event_type)
    {
        if (is_null($event_type)) {
            throw new \InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets datetime_local
     *
     * @return string
     */
    public function getDatetimeLocal()
    {
        return $this->container['datetime_local'];
    }

    /**
     * Sets datetime_local
     *
     * @param string $datetime_local datetime_local
     *
     * @return self
     */
    public function setDatetimeLocal($datetime_local)
    {
        if (is_null($datetime_local)) {
            throw new \InvalidArgumentException('non-nullable datetime_local cannot be null');
        }
        $this->container['datetime_local'] = $datetime_local;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone timezone
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestLocation
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestLocation $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets vehicle_id
     *
     * @return string|null
     */
    public function getVehicleId()
    {
        return $this->container['vehicle_id'];
    }

    /**
     * Sets vehicle_id
     *
     * @param string|null $vehicle_id vehicle_id
     *
     * @return self
     */
    public function setVehicleId($vehicle_id)
    {
        if (is_null($vehicle_id)) {
            throw new \InvalidArgumentException('non-nullable vehicle_id cannot be null');
        }
        $this->container['vehicle_id'] = $vehicle_id;

        return $this;
    }

    /**
     * Gets purpose
     *
     * @return string|null
     */
    public function getPurpose()
    {
        return $this->container['purpose'];
    }

    /**
     * Sets purpose
     *
     * @param string|null $purpose purpose
     *
     * @return self
     */
    public function setPurpose($purpose)
    {
        if (is_null($purpose)) {
            throw new \InvalidArgumentException('non-nullable purpose cannot be null');
        }
        $this->container['purpose'] = $purpose;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes notes
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            throw new \InvalidArgumentException('non-nullable notes cannot be null');
        }
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets odometer
     *
     * @return int|null
     */
    public function getOdometer()
    {
        return $this->container['odometer'];
    }

    /**
     * Sets odometer
     *
     * @param int|null $odometer odometer
     *
     * @return self
     */
    public function setOdometer($odometer)
    {
        if (is_null($odometer)) {
            throw new \InvalidArgumentException('non-nullable odometer cannot be null');
        }
        $this->container['odometer'] = $odometer;

        return $this;
    }

    /**
     * Gets money
     *
     * @return \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestMoney|null
     */
    public function getMoney()
    {
        return $this->container['money'];
    }

    /**
     * Sets money
     *
     * @param \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestMoney|null $money money
     *
     * @return self
     */
    public function setMoney($money)
    {
        if (is_null($money)) {
            throw new \InvalidArgumentException('non-nullable money cannot be null');
        }
        $this->container['money'] = $money;

        return $this;
    }

    /**
     * Gets fueling
     *
     * @return \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestFueling|null
     */
    public function getFueling()
    {
        return $this->container['fueling'];
    }

    /**
     * Sets fueling
     *
     * @param \Platon\\ControlPanel\\Sdk\Model\FinalizeVehicleEventRequestFueling|null $fueling fueling
     *
     * @return self
     */
    public function setFueling($fueling)
    {
        if (is_null($fueling)) {
            throw new \InvalidArgumentException('non-nullable fueling cannot be null');
        }
        $this->container['fueling'] = $fueling;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


