<?php
/**
 * MergeCartItems200ResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Model;

use \ArrayAccess;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * MergeCartItems200ResponseData Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MergeCartItems200ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'mergeCartItems_200_response_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'status' => 'string',
        'merged' => 'bool',
        'from_cname' => 'string',
        'to_cname' => 'string',
        'moved_items' => 'int',
        'merged_items' => 'int',
        'items_count' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'status' => null,
        'merged' => null,
        'from_cname' => null,
        'to_cname' => null,
        'moved_items' => null,
        'merged_items' => null,
        'items_count' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'status' => false,
        'merged' => false,
        'from_cname' => false,
        'to_cname' => false,
        'moved_items' => false,
        'merged_items' => false,
        'items_count' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'status' => 'status',
        'merged' => 'merged',
        'from_cname' => 'from_cname',
        'to_cname' => 'to_cname',
        'moved_items' => 'moved_items',
        'merged_items' => 'merged_items',
        'items_count' => 'items_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'status' => 'setStatus',
        'merged' => 'setMerged',
        'from_cname' => 'setFromCname',
        'to_cname' => 'setToCname',
        'moved_items' => 'setMovedItems',
        'merged_items' => 'setMergedItems',
        'items_count' => 'setItemsCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'status' => 'getStatus',
        'merged' => 'getMerged',
        'from_cname' => 'getFromCname',
        'to_cname' => 'getToCname',
        'moved_items' => 'getMovedItems',
        'merged_items' => 'getMergedItems',
        'items_count' => 'getItemsCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('merged', $data ?? [], null);
        $this->setIfExists('from_cname', $data ?? [], null);
        $this->setIfExists('to_cname', $data ?? [], null);
        $this->setIfExists('moved_items', $data ?? [], null);
        $this->setIfExists('merged_items', $data ?? [], null);
        $this->setIfExists('items_count', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets merged
     *
     * @return bool|null
     */
    public function getMerged()
    {
        return $this->container['merged'];
    }

    /**
     * Sets merged
     *
     * @param bool|null $merged merged
     *
     * @return self
     */
    public function setMerged($merged)
    {
        if (is_null($merged)) {
            throw new \InvalidArgumentException('non-nullable merged cannot be null');
        }
        $this->container['merged'] = $merged;

        return $this;
    }

    /**
     * Gets from_cname
     *
     * @return string|null
     */
    public function getFromCname()
    {
        return $this->container['from_cname'];
    }

    /**
     * Sets from_cname
     *
     * @param string|null $from_cname from_cname
     *
     * @return self
     */
    public function setFromCname($from_cname)
    {
        if (is_null($from_cname)) {
            throw new \InvalidArgumentException('non-nullable from_cname cannot be null');
        }
        $this->container['from_cname'] = $from_cname;

        return $this;
    }

    /**
     * Gets to_cname
     *
     * @return string|null
     */
    public function getToCname()
    {
        return $this->container['to_cname'];
    }

    /**
     * Sets to_cname
     *
     * @param string|null $to_cname to_cname
     *
     * @return self
     */
    public function setToCname($to_cname)
    {
        if (is_null($to_cname)) {
            throw new \InvalidArgumentException('non-nullable to_cname cannot be null');
        }
        $this->container['to_cname'] = $to_cname;

        return $this;
    }

    /**
     * Gets moved_items
     *
     * @return int|null
     */
    public function getMovedItems()
    {
        return $this->container['moved_items'];
    }

    /**
     * Sets moved_items
     *
     * @param int|null $moved_items moved_items
     *
     * @return self
     */
    public function setMovedItems($moved_items)
    {
        if (is_null($moved_items)) {
            throw new \InvalidArgumentException('non-nullable moved_items cannot be null');
        }
        $this->container['moved_items'] = $moved_items;

        return $this;
    }

    /**
     * Gets merged_items
     *
     * @return int|null
     */
    public function getMergedItems()
    {
        return $this->container['merged_items'];
    }

    /**
     * Sets merged_items
     *
     * @param int|null $merged_items merged_items
     *
     * @return self
     */
    public function setMergedItems($merged_items)
    {
        if (is_null($merged_items)) {
            throw new \InvalidArgumentException('non-nullable merged_items cannot be null');
        }
        $this->container['merged_items'] = $merged_items;

        return $this;
    }

    /**
     * Gets items_count
     *
     * @return int|null
     */
    public function getItemsCount()
    {
        return $this->container['items_count'];
    }

    /**
     * Sets items_count
     *
     * @param int|null $items_count items_count
     *
     * @return self
     */
    public function setItemsCount($items_count)
    {
        if (is_null($items_count)) {
            throw new \InvalidArgumentException('non-nullable items_count cannot be null');
        }
        $this->container['items_count'] = $items_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


