<?php
/**
 * AntispamApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Platon\\ControlPanel\\Sdk\ApiException;
use Platon\\ControlPanel\\Sdk\Configuration;
use Platon\\ControlPanel\\Sdk\FormDataProcessor;
use Platon\\ControlPanel\\Sdk\HeaderSelector;
use Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * AntispamApi Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AntispamApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addAntispamMaildata' => [
            'application/json',
        ],
        'checkAntispamMaildataRules' => [
            'application/json',
        ],
        'createAntispamEmailRule' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addAntispamMaildata
     *
     * Add maildata to antispam engine
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\AddAntispamMaildataRequest $add_antispam_maildata_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addAntispamMaildata'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function addAntispamMaildata($add_antispam_maildata_request, string $contentType = self::contentTypes['addAntispamMaildata'][0])
    {
        list($response) = $this->addAntispamMaildataWithHttpInfo($add_antispam_maildata_request, $contentType);
        return $response;
    }

    /**
     * Operation addAntispamMaildataWithHttpInfo
     *
     * Add maildata to antispam engine
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\AddAntispamMaildataRequest $add_antispam_maildata_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addAntispamMaildata'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function addAntispamMaildataWithHttpInfo($add_antispam_maildata_request, string $contentType = self::contentTypes['addAntispamMaildata'][0])
    {
        $request = $this->addAntispamMaildataRequest($add_antispam_maildata_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation addAntispamMaildataAsync
     *
     * Add maildata to antispam engine
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\AddAntispamMaildataRequest $add_antispam_maildata_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addAntispamMaildata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addAntispamMaildataAsync($add_antispam_maildata_request, string $contentType = self::contentTypes['addAntispamMaildata'][0])
    {
        return $this->addAntispamMaildataAsyncWithHttpInfo($add_antispam_maildata_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addAntispamMaildataAsyncWithHttpInfo
     *
     * Add maildata to antispam engine
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\AddAntispamMaildataRequest $add_antispam_maildata_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addAntispamMaildata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addAntispamMaildataAsyncWithHttpInfo($add_antispam_maildata_request, string $contentType = self::contentTypes['addAntispamMaildata'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->addAntispamMaildataRequest($add_antispam_maildata_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addAntispamMaildata'
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\AddAntispamMaildataRequest $add_antispam_maildata_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addAntispamMaildata'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addAntispamMaildataRequest($add_antispam_maildata_request, string $contentType = self::contentTypes['addAntispamMaildata'][0])
    {

        // verify the required parameter 'add_antispam_maildata_request' is set
        if ($add_antispam_maildata_request === null || (is_array($add_antispam_maildata_request) && count($add_antispam_maildata_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $add_antispam_maildata_request when calling addAntispamMaildata'
            );
        }


        $resourcePath = '/antispam/maildata';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($add_antispam_maildata_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($add_antispam_maildata_request));
            } else {
                $httpBody = $add_antispam_maildata_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation checkAntispamMaildataRules
     *
     * Check maildata against existing antispam rules
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CheckAntispamMaildataRulesRequest $check_antispam_maildata_rules_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkAntispamMaildataRules'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function checkAntispamMaildataRules($check_antispam_maildata_rules_request, string $contentType = self::contentTypes['checkAntispamMaildataRules'][0])
    {
        list($response) = $this->checkAntispamMaildataRulesWithHttpInfo($check_antispam_maildata_rules_request, $contentType);
        return $response;
    }

    /**
     * Operation checkAntispamMaildataRulesWithHttpInfo
     *
     * Check maildata against existing antispam rules
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CheckAntispamMaildataRulesRequest $check_antispam_maildata_rules_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkAntispamMaildataRules'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkAntispamMaildataRulesWithHttpInfo($check_antispam_maildata_rules_request, string $contentType = self::contentTypes['checkAntispamMaildataRules'][0])
    {
        $request = $this->checkAntispamMaildataRulesRequest($check_antispam_maildata_rules_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation checkAntispamMaildataRulesAsync
     *
     * Check maildata against existing antispam rules
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CheckAntispamMaildataRulesRequest $check_antispam_maildata_rules_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkAntispamMaildataRules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkAntispamMaildataRulesAsync($check_antispam_maildata_rules_request, string $contentType = self::contentTypes['checkAntispamMaildataRules'][0])
    {
        return $this->checkAntispamMaildataRulesAsyncWithHttpInfo($check_antispam_maildata_rules_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkAntispamMaildataRulesAsyncWithHttpInfo
     *
     * Check maildata against existing antispam rules
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CheckAntispamMaildataRulesRequest $check_antispam_maildata_rules_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkAntispamMaildataRules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkAntispamMaildataRulesAsyncWithHttpInfo($check_antispam_maildata_rules_request, string $contentType = self::contentTypes['checkAntispamMaildataRules'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->checkAntispamMaildataRulesRequest($check_antispam_maildata_rules_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkAntispamMaildataRules'
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CheckAntispamMaildataRulesRequest $check_antispam_maildata_rules_request Maildata payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkAntispamMaildataRules'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkAntispamMaildataRulesRequest($check_antispam_maildata_rules_request, string $contentType = self::contentTypes['checkAntispamMaildataRules'][0])
    {

        // verify the required parameter 'check_antispam_maildata_rules_request' is set
        if ($check_antispam_maildata_rules_request === null || (is_array($check_antispam_maildata_rules_request) && count($check_antispam_maildata_rules_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $check_antispam_maildata_rules_request when calling checkAntispamMaildataRules'
            );
        }


        $resourcePath = '/antispam/maildata/check';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($check_antispam_maildata_rules_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($check_antispam_maildata_rules_request));
            } else {
                $httpBody = $check_antispam_maildata_rules_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createAntispamEmailRule
     *
     * Create antispam email rule or increment existing rule hitcount
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateAntispamEmailRuleRequest $create_antispam_email_rule_request Antispam email rule payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAntispamEmailRule'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function createAntispamEmailRule($create_antispam_email_rule_request, string $contentType = self::contentTypes['createAntispamEmailRule'][0])
    {
        list($response) = $this->createAntispamEmailRuleWithHttpInfo($create_antispam_email_rule_request, $contentType);
        return $response;
    }

    /**
     * Operation createAntispamEmailRuleWithHttpInfo
     *
     * Create antispam email rule or increment existing rule hitcount
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateAntispamEmailRuleRequest $create_antispam_email_rule_request Antispam email rule payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAntispamEmailRule'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAntispamEmailRuleWithHttpInfo($create_antispam_email_rule_request, string $contentType = self::contentTypes['createAntispamEmailRule'][0])
    {
        $request = $this->createAntispamEmailRuleRequest($create_antispam_email_rule_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAntispamEmailRuleAsync
     *
     * Create antispam email rule or increment existing rule hitcount
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateAntispamEmailRuleRequest $create_antispam_email_rule_request Antispam email rule payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAntispamEmailRule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAntispamEmailRuleAsync($create_antispam_email_rule_request, string $contentType = self::contentTypes['createAntispamEmailRule'][0])
    {
        return $this->createAntispamEmailRuleAsyncWithHttpInfo($create_antispam_email_rule_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAntispamEmailRuleAsyncWithHttpInfo
     *
     * Create antispam email rule or increment existing rule hitcount
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateAntispamEmailRuleRequest $create_antispam_email_rule_request Antispam email rule payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAntispamEmailRule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAntispamEmailRuleAsyncWithHttpInfo($create_antispam_email_rule_request, string $contentType = self::contentTypes['createAntispamEmailRule'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->createAntispamEmailRuleRequest($create_antispam_email_rule_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAntispamEmailRule'
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateAntispamEmailRuleRequest $create_antispam_email_rule_request Antispam email rule payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAntispamEmailRule'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAntispamEmailRuleRequest($create_antispam_email_rule_request, string $contentType = self::contentTypes['createAntispamEmailRule'][0])
    {

        // verify the required parameter 'create_antispam_email_rule_request' is set
        if ($create_antispam_email_rule_request === null || (is_array($create_antispam_email_rule_request) && count($create_antispam_email_rule_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_antispam_email_rule_request when calling createAntispamEmailRule'
            );
        }


        $resourcePath = '/antispam/rules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_antispam_email_rule_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_antispam_email_rule_request));
            } else {
                $httpBody = $create_antispam_email_rule_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
