<?php
/**
 * DNSApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Platon\\ControlPanel\\Sdk\ApiException;
use Platon\\ControlPanel\\Sdk\Configuration;
use Platon\\ControlPanel\\Sdk\FormDataProcessor;
use Platon\\ControlPanel\\Sdk\HeaderSelector;
use Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * DNSApi Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DNSApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createDnsRecord' => [
            'application/json',
        ],
        'deleteDnsRecord' => [
            'application/json',
        ],
        'getDnsRecords' => [
            'application/json',
        ],
        'updateDnsRecord' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createDnsRecord
     *
     * Create DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecordRequest $create_dns_record_request DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function createDnsRecord($domain, $create_dns_record_request, string $contentType = self::contentTypes['createDnsRecord'][0])
    {
        list($response) = $this->createDnsRecordWithHttpInfo($domain, $create_dns_record_request, $contentType);
        return $response;
    }

    /**
     * Operation createDnsRecordWithHttpInfo
     *
     * Create DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecordRequest $create_dns_record_request DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createDnsRecordWithHttpInfo($domain, $create_dns_record_request, string $contentType = self::contentTypes['createDnsRecord'][0])
    {
        $request = $this->createDnsRecordRequest($domain, $create_dns_record_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createDnsRecordAsync
     *
     * Create DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecordRequest $create_dns_record_request DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDnsRecordAsync($domain, $create_dns_record_request, string $contentType = self::contentTypes['createDnsRecord'][0])
    {
        return $this->createDnsRecordAsyncWithHttpInfo($domain, $create_dns_record_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createDnsRecordAsyncWithHttpInfo
     *
     * Create DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecordRequest $create_dns_record_request DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDnsRecordAsyncWithHttpInfo($domain, $create_dns_record_request, string $contentType = self::contentTypes['createDnsRecord'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->createDnsRecordRequest($domain, $create_dns_record_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createDnsRecord'
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecordRequest $create_dns_record_request DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createDnsRecordRequest($domain, $create_dns_record_request, string $contentType = self::contentTypes['createDnsRecord'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling createDnsRecord'
            );
        }

        // verify the required parameter 'create_dns_record_request' is set
        if ($create_dns_record_request === null || (is_array($create_dns_record_request) && count($create_dns_record_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_dns_record_request when calling createDnsRecord'
            );
        }


        $resourcePath = '/dns/{domain}/records';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_dns_record_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_dns_record_request));
            } else {
                $httpBody = $create_dns_record_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteDnsRecord
     *
     * Delete DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function deleteDnsRecord($domain, $record_id, string $contentType = self::contentTypes['deleteDnsRecord'][0])
    {
        list($response) = $this->deleteDnsRecordWithHttpInfo($domain, $record_id, $contentType);
        return $response;
    }

    /**
     * Operation deleteDnsRecordWithHttpInfo
     *
     * Delete DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteDnsRecordWithHttpInfo($domain, $record_id, string $contentType = self::contentTypes['deleteDnsRecord'][0])
    {
        $request = $this->deleteDnsRecordRequest($domain, $record_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteDnsRecordAsync
     *
     * Delete DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDnsRecordAsync($domain, $record_id, string $contentType = self::contentTypes['deleteDnsRecord'][0])
    {
        return $this->deleteDnsRecordAsyncWithHttpInfo($domain, $record_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteDnsRecordAsyncWithHttpInfo
     *
     * Delete DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDnsRecordAsyncWithHttpInfo($domain, $record_id, string $contentType = self::contentTypes['deleteDnsRecord'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->deleteDnsRecordRequest($domain, $record_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteDnsRecord'
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteDnsRecordRequest($domain, $record_id, string $contentType = self::contentTypes['deleteDnsRecord'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling deleteDnsRecord'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling deleteDnsRecord'
            );
        }


        $resourcePath = '/dns/{domain}/records/{recordId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDnsRecords
     *
     * Get DNS records by domain
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $type Filter records by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDnsRecords'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response
     */
    public function getDnsRecords($domain, $type = null, string $contentType = self::contentTypes['getDnsRecords'][0])
    {
        list($response) = $this->getDnsRecordsWithHttpInfo($domain, $type, $contentType);
        return $response;
    }

    /**
     * Operation getDnsRecordsWithHttpInfo
     *
     * Get DNS records by domain
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $type Filter records by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDnsRecords'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDnsRecordsWithHttpInfo($domain, $type = null, string $contentType = self::contentTypes['getDnsRecords'][0])
    {
        $request = $this->getDnsRecordsRequest($domain, $type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDnsRecordsAsync
     *
     * Get DNS records by domain
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $type Filter records by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDnsRecords'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDnsRecordsAsync($domain, $type = null, string $contentType = self::contentTypes['getDnsRecords'][0])
    {
        return $this->getDnsRecordsAsyncWithHttpInfo($domain, $type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDnsRecordsAsyncWithHttpInfo
     *
     * Get DNS records by domain
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $type Filter records by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDnsRecords'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDnsRecordsAsyncWithHttpInfo($domain, $type = null, string $contentType = self::contentTypes['getDnsRecords'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\GetDnsRecords200Response';
        $request = $this->getDnsRecordsRequest($domain, $type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDnsRecords'
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $type Filter records by type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDnsRecords'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDnsRecordsRequest($domain, $type = null, string $contentType = self::contentTypes['getDnsRecords'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling getDnsRecords'
            );
        }



        $resourcePath = '/dns/{domain}/records';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateDnsRecord
     *
     * Update DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\UpdateDnsRecordRequest $update_dns_record_request Partial DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function updateDnsRecord($domain, $record_id, $update_dns_record_request, string $contentType = self::contentTypes['updateDnsRecord'][0])
    {
        list($response) = $this->updateDnsRecordWithHttpInfo($domain, $record_id, $update_dns_record_request, $contentType);
        return $response;
    }

    /**
     * Operation updateDnsRecordWithHttpInfo
     *
     * Update DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\UpdateDnsRecordRequest $update_dns_record_request Partial DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDnsRecord'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateDnsRecordWithHttpInfo($domain, $record_id, $update_dns_record_request, string $contentType = self::contentTypes['updateDnsRecord'][0])
    {
        $request = $this->updateDnsRecordRequest($domain, $record_id, $update_dns_record_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateDnsRecordAsync
     *
     * Update DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\UpdateDnsRecordRequest $update_dns_record_request Partial DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDnsRecordAsync($domain, $record_id, $update_dns_record_request, string $contentType = self::contentTypes['updateDnsRecord'][0])
    {
        return $this->updateDnsRecordAsyncWithHttpInfo($domain, $record_id, $update_dns_record_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateDnsRecordAsyncWithHttpInfo
     *
     * Update DNS record
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\UpdateDnsRecordRequest $update_dns_record_request Partial DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDnsRecordAsyncWithHttpInfo($domain, $record_id, $update_dns_record_request, string $contentType = self::contentTypes['updateDnsRecord'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->updateDnsRecordRequest($domain, $record_id, $update_dns_record_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateDnsRecord'
     *
     * @param  string $domain Domain name (required)
     * @param  int $record_id Record ID (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\UpdateDnsRecordRequest $update_dns_record_request Partial DNS record payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDnsRecord'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateDnsRecordRequest($domain, $record_id, $update_dns_record_request, string $contentType = self::contentTypes['updateDnsRecord'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling updateDnsRecord'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling updateDnsRecord'
            );
        }

        // verify the required parameter 'update_dns_record_request' is set
        if ($update_dns_record_request === null || (is_array($update_dns_record_request) && count($update_dns_record_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_dns_record_request when calling updateDnsRecord'
            );
        }


        $resourcePath = '/dns/{domain}/records/{recordId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_dns_record_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_dns_record_request));
            } else {
                $httpBody = $update_dns_record_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
