<?php
/**
 * DomainApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Platon\\ControlPanel\\Sdk\ApiException;
use Platon\\ControlPanel\\Sdk\Configuration;
use Platon\\ControlPanel\\Sdk\FormDataProcessor;
use Platon\\ControlPanel\\Sdk\HeaderSelector;
use Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * DomainApi Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'changeDomainNameservers' => [
            'application/json',
        ],
        'closeDomain' => [
            'application/json',
        ],
        'getDomainInfo' => [
            'application/json',
        ],
        'listDomains' => [
            'application/json',
        ],
        'registerDomain' => [
            'application/json',
        ],
        'renewDomain' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation changeDomainNameservers
     *
     * Change domain nameservers
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeDomainNameserversRequest $change_domain_nameservers_request Nameserver payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeDomainNameservers'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function changeDomainNameservers($domain, $change_domain_nameservers_request, string $contentType = self::contentTypes['changeDomainNameservers'][0])
    {
        list($response) = $this->changeDomainNameserversWithHttpInfo($domain, $change_domain_nameservers_request, $contentType);
        return $response;
    }

    /**
     * Operation changeDomainNameserversWithHttpInfo
     *
     * Change domain nameservers
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeDomainNameserversRequest $change_domain_nameservers_request Nameserver payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeDomainNameservers'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function changeDomainNameserversWithHttpInfo($domain, $change_domain_nameservers_request, string $contentType = self::contentTypes['changeDomainNameservers'][0])
    {
        $request = $this->changeDomainNameserversRequest($domain, $change_domain_nameservers_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation changeDomainNameserversAsync
     *
     * Change domain nameservers
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeDomainNameserversRequest $change_domain_nameservers_request Nameserver payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeDomainNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeDomainNameserversAsync($domain, $change_domain_nameservers_request, string $contentType = self::contentTypes['changeDomainNameservers'][0])
    {
        return $this->changeDomainNameserversAsyncWithHttpInfo($domain, $change_domain_nameservers_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation changeDomainNameserversAsyncWithHttpInfo
     *
     * Change domain nameservers
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeDomainNameserversRequest $change_domain_nameservers_request Nameserver payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeDomainNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeDomainNameserversAsyncWithHttpInfo($domain, $change_domain_nameservers_request, string $contentType = self::contentTypes['changeDomainNameservers'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->changeDomainNameserversRequest($domain, $change_domain_nameservers_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'changeDomainNameservers'
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeDomainNameserversRequest $change_domain_nameservers_request Nameserver payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeDomainNameservers'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function changeDomainNameserversRequest($domain, $change_domain_nameservers_request, string $contentType = self::contentTypes['changeDomainNameservers'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling changeDomainNameservers'
            );
        }

        // verify the required parameter 'change_domain_nameservers_request' is set
        if ($change_domain_nameservers_request === null || (is_array($change_domain_nameservers_request) && count($change_domain_nameservers_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $change_domain_nameservers_request when calling changeDomainNameservers'
            );
        }


        $resourcePath = '/domains/{domain}/nameservers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($change_domain_nameservers_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($change_domain_nameservers_request));
            } else {
                $httpBody = $change_domain_nameservers_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation closeDomain
     *
     * Close external customer domain product
     *
     * @param  string $domain Domain name (required)
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['closeDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function closeDomain($domain, $cname, string $contentType = self::contentTypes['closeDomain'][0])
    {
        list($response) = $this->closeDomainWithHttpInfo($domain, $cname, $contentType);
        return $response;
    }

    /**
     * Operation closeDomainWithHttpInfo
     *
     * Close external customer domain product
     *
     * @param  string $domain Domain name (required)
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['closeDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function closeDomainWithHttpInfo($domain, $cname, string $contentType = self::contentTypes['closeDomain'][0])
    {
        $request = $this->closeDomainRequest($domain, $cname, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation closeDomainAsync
     *
     * Close external customer domain product
     *
     * @param  string $domain Domain name (required)
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['closeDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function closeDomainAsync($domain, $cname, string $contentType = self::contentTypes['closeDomain'][0])
    {
        return $this->closeDomainAsyncWithHttpInfo($domain, $cname, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation closeDomainAsyncWithHttpInfo
     *
     * Close external customer domain product
     *
     * @param  string $domain Domain name (required)
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['closeDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function closeDomainAsyncWithHttpInfo($domain, $cname, string $contentType = self::contentTypes['closeDomain'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->closeDomainRequest($domain, $cname, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'closeDomain'
     *
     * @param  string $domain Domain name (required)
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['closeDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function closeDomainRequest($domain, $cname, string $contentType = self::contentTypes['closeDomain'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling closeDomain'
            );
        }

        // verify the required parameter 'cname' is set
        if ($cname === null || (is_array($cname) && count($cname) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cname when calling closeDomain'
            );
        }


        $resourcePath = '/domains/{domain}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cname,
            'cname', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDomainInfo
     *
     * Get domain information and availability
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $cname Customer name for product context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDomainInfo'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function getDomainInfo($domain, $cname = null, string $contentType = self::contentTypes['getDomainInfo'][0])
    {
        list($response) = $this->getDomainInfoWithHttpInfo($domain, $cname, $contentType);
        return $response;
    }

    /**
     * Operation getDomainInfoWithHttpInfo
     *
     * Get domain information and availability
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $cname Customer name for product context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDomainInfo'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDomainInfoWithHttpInfo($domain, $cname = null, string $contentType = self::contentTypes['getDomainInfo'][0])
    {
        $request = $this->getDomainInfoRequest($domain, $cname, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDomainInfoAsync
     *
     * Get domain information and availability
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $cname Customer name for product context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDomainInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDomainInfoAsync($domain, $cname = null, string $contentType = self::contentTypes['getDomainInfo'][0])
    {
        return $this->getDomainInfoAsyncWithHttpInfo($domain, $cname, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDomainInfoAsyncWithHttpInfo
     *
     * Get domain information and availability
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $cname Customer name for product context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDomainInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDomainInfoAsyncWithHttpInfo($domain, $cname = null, string $contentType = self::contentTypes['getDomainInfo'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->getDomainInfoRequest($domain, $cname, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDomainInfo'
     *
     * @param  string $domain Domain name (required)
     * @param  string|null $cname Customer name for product context (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDomainInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDomainInfoRequest($domain, $cname = null, string $contentType = self::contentTypes['getDomainInfo'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling getDomainInfo'
            );
        }



        $resourcePath = '/domains/{domain}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cname,
            'cname', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDomains
     *
     * List customer domains
     *
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDomains'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\ListDomains200Response
     */
    public function listDomains($cname, string $contentType = self::contentTypes['listDomains'][0])
    {
        list($response) = $this->listDomainsWithHttpInfo($cname, $contentType);
        return $response;
    }

    /**
     * Operation listDomainsWithHttpInfo
     *
     * List customer domains
     *
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDomains'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\ListDomains200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listDomainsWithHttpInfo($cname, string $contentType = self::contentTypes['listDomains'][0])
    {
        $request = $this->listDomainsRequest($cname, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\ListDomains200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\ListDomains200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\ListDomains200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listDomainsAsync
     *
     * List customer domains
     *
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDomainsAsync($cname, string $contentType = self::contentTypes['listDomains'][0])
    {
        return $this->listDomainsAsyncWithHttpInfo($cname, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDomainsAsyncWithHttpInfo
     *
     * List customer domains
     *
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDomainsAsyncWithHttpInfo($cname, string $contentType = self::contentTypes['listDomains'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\ListDomains200Response';
        $request = $this->listDomainsRequest($cname, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDomains'
     *
     * @param  string $cname Customer name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDomainsRequest($cname, string $contentType = self::contentTypes['listDomains'][0])
    {

        // verify the required parameter 'cname' is set
        if ($cname === null || (is_array($cname) && count($cname) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cname when calling listDomains'
            );
        }


        $resourcePath = '/domains';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cname,
            'cname', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation registerDomain
     *
     * Register domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RegisterDomainRequest $register_domain_request Domain registration payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['registerDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function registerDomain($domain, $register_domain_request, string $contentType = self::contentTypes['registerDomain'][0])
    {
        list($response) = $this->registerDomainWithHttpInfo($domain, $register_domain_request, $contentType);
        return $response;
    }

    /**
     * Operation registerDomainWithHttpInfo
     *
     * Register domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RegisterDomainRequest $register_domain_request Domain registration payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['registerDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function registerDomainWithHttpInfo($domain, $register_domain_request, string $contentType = self::contentTypes['registerDomain'][0])
    {
        $request = $this->registerDomainRequest($domain, $register_domain_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation registerDomainAsync
     *
     * Register domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RegisterDomainRequest $register_domain_request Domain registration payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['registerDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function registerDomainAsync($domain, $register_domain_request, string $contentType = self::contentTypes['registerDomain'][0])
    {
        return $this->registerDomainAsyncWithHttpInfo($domain, $register_domain_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation registerDomainAsyncWithHttpInfo
     *
     * Register domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RegisterDomainRequest $register_domain_request Domain registration payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['registerDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function registerDomainAsyncWithHttpInfo($domain, $register_domain_request, string $contentType = self::contentTypes['registerDomain'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->registerDomainRequest($domain, $register_domain_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'registerDomain'
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RegisterDomainRequest $register_domain_request Domain registration payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['registerDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function registerDomainRequest($domain, $register_domain_request, string $contentType = self::contentTypes['registerDomain'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling registerDomain'
            );
        }

        // verify the required parameter 'register_domain_request' is set
        if ($register_domain_request === null || (is_array($register_domain_request) && count($register_domain_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $register_domain_request when calling registerDomain'
            );
        }


        $resourcePath = '/domains/{domain}/register';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($register_domain_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($register_domain_request));
            } else {
                $httpBody = $register_domain_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation renewDomain
     *
     * Renew domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RenewDomainRequest|null $renew_domain_request Domain renewal payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['renewDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function renewDomain($domain, $renew_domain_request = null, string $contentType = self::contentTypes['renewDomain'][0])
    {
        list($response) = $this->renewDomainWithHttpInfo($domain, $renew_domain_request, $contentType);
        return $response;
    }

    /**
     * Operation renewDomainWithHttpInfo
     *
     * Renew domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RenewDomainRequest|null $renew_domain_request Domain renewal payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['renewDomain'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function renewDomainWithHttpInfo($domain, $renew_domain_request = null, string $contentType = self::contentTypes['renewDomain'][0])
    {
        $request = $this->renewDomainRequest($domain, $renew_domain_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation renewDomainAsync
     *
     * Renew domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RenewDomainRequest|null $renew_domain_request Domain renewal payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['renewDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function renewDomainAsync($domain, $renew_domain_request = null, string $contentType = self::contentTypes['renewDomain'][0])
    {
        return $this->renewDomainAsyncWithHttpInfo($domain, $renew_domain_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation renewDomainAsyncWithHttpInfo
     *
     * Renew domain
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RenewDomainRequest|null $renew_domain_request Domain renewal payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['renewDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function renewDomainAsyncWithHttpInfo($domain, $renew_domain_request = null, string $contentType = self::contentTypes['renewDomain'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->renewDomainRequest($domain, $renew_domain_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'renewDomain'
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\RenewDomainRequest|null $renew_domain_request Domain renewal payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['renewDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function renewDomainRequest($domain, $renew_domain_request = null, string $contentType = self::contentTypes['renewDomain'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling renewDomain'
            );
        }



        $resourcePath = '/domains/{domain}/renew';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($renew_domain_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($renew_domain_request));
            } else {
                $httpBody = $renew_domain_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
