<?php
/**
 * EmailApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Platon\\ControlPanel\\Sdk\ApiException;
use Platon\\ControlPanel\\Sdk\Configuration;
use Platon\\ControlPanel\\Sdk\FormDataProcessor;
use Platon\\ControlPanel\\Sdk\HeaderSelector;
use Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * EmailApi Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'changeMailboxPassword' => [
            'application/json',
        ],
        'createMailbox' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation changeMailboxPassword
     *
     * Change mailbox password
     *
     * @param  string $domain Domain name (required)
     * @param  string $username Mailbox username (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeMailboxPasswordRequest $change_mailbox_password_request Mailbox password payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeMailboxPassword'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function changeMailboxPassword($domain, $username, $change_mailbox_password_request, string $contentType = self::contentTypes['changeMailboxPassword'][0])
    {
        list($response) = $this->changeMailboxPasswordWithHttpInfo($domain, $username, $change_mailbox_password_request, $contentType);
        return $response;
    }

    /**
     * Operation changeMailboxPasswordWithHttpInfo
     *
     * Change mailbox password
     *
     * @param  string $domain Domain name (required)
     * @param  string $username Mailbox username (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeMailboxPasswordRequest $change_mailbox_password_request Mailbox password payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeMailboxPassword'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function changeMailboxPasswordWithHttpInfo($domain, $username, $change_mailbox_password_request, string $contentType = self::contentTypes['changeMailboxPassword'][0])
    {
        $request = $this->changeMailboxPasswordRequest($domain, $username, $change_mailbox_password_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation changeMailboxPasswordAsync
     *
     * Change mailbox password
     *
     * @param  string $domain Domain name (required)
     * @param  string $username Mailbox username (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeMailboxPasswordRequest $change_mailbox_password_request Mailbox password payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeMailboxPassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeMailboxPasswordAsync($domain, $username, $change_mailbox_password_request, string $contentType = self::contentTypes['changeMailboxPassword'][0])
    {
        return $this->changeMailboxPasswordAsyncWithHttpInfo($domain, $username, $change_mailbox_password_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation changeMailboxPasswordAsyncWithHttpInfo
     *
     * Change mailbox password
     *
     * @param  string $domain Domain name (required)
     * @param  string $username Mailbox username (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeMailboxPasswordRequest $change_mailbox_password_request Mailbox password payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeMailboxPassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeMailboxPasswordAsyncWithHttpInfo($domain, $username, $change_mailbox_password_request, string $contentType = self::contentTypes['changeMailboxPassword'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->changeMailboxPasswordRequest($domain, $username, $change_mailbox_password_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'changeMailboxPassword'
     *
     * @param  string $domain Domain name (required)
     * @param  string $username Mailbox username (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\ChangeMailboxPasswordRequest $change_mailbox_password_request Mailbox password payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['changeMailboxPassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function changeMailboxPasswordRequest($domain, $username, $change_mailbox_password_request, string $contentType = self::contentTypes['changeMailboxPassword'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling changeMailboxPassword'
            );
        }

        // verify the required parameter 'username' is set
        if ($username === null || (is_array($username) && count($username) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $username when calling changeMailboxPassword'
            );
        }

        // verify the required parameter 'change_mailbox_password_request' is set
        if ($change_mailbox_password_request === null || (is_array($change_mailbox_password_request) && count($change_mailbox_password_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $change_mailbox_password_request when calling changeMailboxPassword'
            );
        }


        $resourcePath = '/email/{domain}/mailboxes/{username}/password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }
        // path params
        if ($username !== null) {
            $resourcePath = str_replace(
                '{' . 'username' . '}',
                ObjectSerializer::toPathValue($username),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($change_mailbox_password_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($change_mailbox_password_request));
            } else {
                $httpBody = $change_mailbox_password_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createMailbox
     *
     * Create mailbox
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateMailboxRequest $create_mailbox_request Mailbox payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMailbox'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response
     */
    public function createMailbox($domain, $create_mailbox_request, string $contentType = self::contentTypes['createMailbox'][0])
    {
        list($response) = $this->createMailboxWithHttpInfo($domain, $create_mailbox_request, $contentType);
        return $response;
    }

    /**
     * Operation createMailboxWithHttpInfo
     *
     * Create mailbox
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateMailboxRequest $create_mailbox_request Mailbox payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMailbox'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMailboxWithHttpInfo($domain, $create_mailbox_request, string $contentType = self::contentTypes['createMailbox'][0])
    {
        $request = $this->createMailboxRequest($domain, $create_mailbox_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createMailboxAsync
     *
     * Create mailbox
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateMailboxRequest $create_mailbox_request Mailbox payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMailbox'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMailboxAsync($domain, $create_mailbox_request, string $contentType = self::contentTypes['createMailbox'][0])
    {
        return $this->createMailboxAsyncWithHttpInfo($domain, $create_mailbox_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMailboxAsyncWithHttpInfo
     *
     * Create mailbox
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateMailboxRequest $create_mailbox_request Mailbox payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMailbox'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMailboxAsyncWithHttpInfo($domain, $create_mailbox_request, string $contentType = self::contentTypes['createMailbox'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateDnsRecord200Response';
        $request = $this->createMailboxRequest($domain, $create_mailbox_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMailbox'
     *
     * @param  string $domain Domain name (required)
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateMailboxRequest $create_mailbox_request Mailbox payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMailbox'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMailboxRequest($domain, $create_mailbox_request, string $contentType = self::contentTypes['createMailbox'][0])
    {

        // verify the required parameter 'domain' is set
        if ($domain === null || (is_array($domain) && count($domain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain when calling createMailbox'
            );
        }

        // verify the required parameter 'create_mailbox_request' is set
        if ($create_mailbox_request === null || (is_array($create_mailbox_request) && count($create_mailbox_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_mailbox_request when calling createMailbox'
            );
        }


        $resourcePath = '/email/{domain}/mailboxes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain !== null) {
            $resourcePath = str_replace(
                '{' . 'domain' . '}',
                ObjectSerializer::toPathValue($domain),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_mailbox_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_mailbox_request));
            } else {
                $httpBody = $create_mailbox_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
