<?php
/**
 * OAuthApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Platon\\ControlPanel\\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Platon\\ControlPanel\\Sdk\ApiException;
use Platon\\ControlPanel\\Sdk\Configuration;
use Platon\\ControlPanel\\Sdk\FormDataProcessor;
use Platon\\ControlPanel\\Sdk\HeaderSelector;
use Platon\\ControlPanel\\Sdk\ObjectSerializer;

/**
 * OAuthApi Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OAuthApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createOauthRequest' => [
            'application/json',
        ],
        'deleteOauthToken' => [
            'application/json',
        ],
        'getOauthScopes' => [
            'application/json',
        ],
        'refreshOauthToken' => [
            'application/json',
        ],
        'verifyOauthRequest' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createOauthRequest
     *
     * Create OAuth request
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequestRequest|null $create_oauth_request_request OAuth create payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOauthRequest'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response
     */
    public function createOauthRequest($create_oauth_request_request = null, string $contentType = self::contentTypes['createOauthRequest'][0])
    {
        list($response) = $this->createOauthRequestWithHttpInfo($create_oauth_request_request, $contentType);
        return $response;
    }

    /**
     * Operation createOauthRequestWithHttpInfo
     *
     * Create OAuth request
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequestRequest|null $create_oauth_request_request OAuth create payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOauthRequest'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createOauthRequestWithHttpInfo($create_oauth_request_request = null, string $contentType = self::contentTypes['createOauthRequest'][0])
    {
        $request = $this->createOauthRequestRequest($create_oauth_request_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createOauthRequestAsync
     *
     * Create OAuth request
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequestRequest|null $create_oauth_request_request OAuth create payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOauthRequestAsync($create_oauth_request_request = null, string $contentType = self::contentTypes['createOauthRequest'][0])
    {
        return $this->createOauthRequestAsyncWithHttpInfo($create_oauth_request_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createOauthRequestAsyncWithHttpInfo
     *
     * Create OAuth request
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequestRequest|null $create_oauth_request_request OAuth create payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOauthRequestAsyncWithHttpInfo($create_oauth_request_request = null, string $contentType = self::contentTypes['createOauthRequest'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\CreateOauthRequest200Response';
        $request = $this->createOauthRequestRequest($create_oauth_request_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createOauthRequest'
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\CreateOauthRequestRequest|null $create_oauth_request_request OAuth create payload (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createOauthRequestRequest($create_oauth_request_request = null, string $contentType = self::contentTypes['createOauthRequest'][0])
    {



        $resourcePath = '/oauth/requests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_oauth_request_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_oauth_request_request));
            } else {
                $httpBody = $create_oauth_request_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteOauthToken
     *
     * Delete OAuth token
     *
     * @param  string $token OAuth token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteOauthToken'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response
     */
    public function deleteOauthToken($token, string $contentType = self::contentTypes['deleteOauthToken'][0])
    {
        list($response) = $this->deleteOauthTokenWithHttpInfo($token, $contentType);
        return $response;
    }

    /**
     * Operation deleteOauthTokenWithHttpInfo
     *
     * Delete OAuth token
     *
     * @param  string $token OAuth token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteOauthToken'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteOauthTokenWithHttpInfo($token, string $contentType = self::contentTypes['deleteOauthToken'][0])
    {
        $request = $this->deleteOauthTokenRequest($token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteOauthTokenAsync
     *
     * Delete OAuth token
     *
     * @param  string $token OAuth token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteOauthTokenAsync($token, string $contentType = self::contentTypes['deleteOauthToken'][0])
    {
        return $this->deleteOauthTokenAsyncWithHttpInfo($token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteOauthTokenAsyncWithHttpInfo
     *
     * Delete OAuth token
     *
     * @param  string $token OAuth token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteOauthTokenAsyncWithHttpInfo($token, string $contentType = self::contentTypes['deleteOauthToken'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\DeleteOauthToken200Response';
        $request = $this->deleteOauthTokenRequest($token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteOauthToken'
     *
     * @param  string $token OAuth token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteOauthTokenRequest($token, string $contentType = self::contentTypes['deleteOauthToken'][0])
    {

        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling deleteOauthToken'
            );
        }


        $resourcePath = '/oauth/tokens';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOauthScopes
     *
     * List available OAuth scopes
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOauthScopes'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response
     */
    public function getOauthScopes(string $contentType = self::contentTypes['getOauthScopes'][0])
    {
        list($response) = $this->getOauthScopesWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getOauthScopesWithHttpInfo
     *
     * List available OAuth scopes
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOauthScopes'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOauthScopesWithHttpInfo(string $contentType = self::contentTypes['getOauthScopes'][0])
    {
        $request = $this->getOauthScopesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOauthScopesAsync
     *
     * List available OAuth scopes
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOauthScopes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOauthScopesAsync(string $contentType = self::contentTypes['getOauthScopes'][0])
    {
        return $this->getOauthScopesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOauthScopesAsyncWithHttpInfo
     *
     * List available OAuth scopes
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOauthScopes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOauthScopesAsyncWithHttpInfo(string $contentType = self::contentTypes['getOauthScopes'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\GetOauthScopes200Response';
        $request = $this->getOauthScopesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOauthScopes'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOauthScopes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOauthScopesRequest(string $contentType = self::contentTypes['getOauthScopes'][0])
    {


        $resourcePath = '/oauth/scopes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refreshOauthToken
     *
     * Refresh OAuth token
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\RefreshOauthTokenRequest $refresh_oauth_token_request OAuth refresh payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshOauthToken'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response
     */
    public function refreshOauthToken($refresh_oauth_token_request, string $contentType = self::contentTypes['refreshOauthToken'][0])
    {
        list($response) = $this->refreshOauthTokenWithHttpInfo($refresh_oauth_token_request, $contentType);
        return $response;
    }

    /**
     * Operation refreshOauthTokenWithHttpInfo
     *
     * Refresh OAuth token
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\RefreshOauthTokenRequest $refresh_oauth_token_request OAuth refresh payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshOauthToken'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function refreshOauthTokenWithHttpInfo($refresh_oauth_token_request, string $contentType = self::contentTypes['refreshOauthToken'][0])
    {
        $request = $this->refreshOauthTokenRequest($refresh_oauth_token_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation refreshOauthTokenAsync
     *
     * Refresh OAuth token
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\RefreshOauthTokenRequest $refresh_oauth_token_request OAuth refresh payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refreshOauthTokenAsync($refresh_oauth_token_request, string $contentType = self::contentTypes['refreshOauthToken'][0])
    {
        return $this->refreshOauthTokenAsyncWithHttpInfo($refresh_oauth_token_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refreshOauthTokenAsyncWithHttpInfo
     *
     * Refresh OAuth token
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\RefreshOauthTokenRequest $refresh_oauth_token_request OAuth refresh payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refreshOauthTokenAsyncWithHttpInfo($refresh_oauth_token_request, string $contentType = self::contentTypes['refreshOauthToken'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response';
        $request = $this->refreshOauthTokenRequest($refresh_oauth_token_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refreshOauthToken'
     *
     * @param  \Platon\\ControlPanel\\Sdk\Model\RefreshOauthTokenRequest $refresh_oauth_token_request OAuth refresh payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refreshOauthToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refreshOauthTokenRequest($refresh_oauth_token_request, string $contentType = self::contentTypes['refreshOauthToken'][0])
    {

        // verify the required parameter 'refresh_oauth_token_request' is set
        if ($refresh_oauth_token_request === null || (is_array($refresh_oauth_token_request) && count($refresh_oauth_token_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $refresh_oauth_token_request when calling refreshOauthToken'
            );
        }


        $resourcePath = '/oauth/tokens/refresh';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($refresh_oauth_token_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($refresh_oauth_token_request));
            } else {
                $httpBody = $refresh_oauth_token_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation verifyOauthRequest
     *
     * Verify OAuth request
     *
     * @param  string $verify_token Verify token from OAuth create response (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyOauthRequest'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response
     */
    public function verifyOauthRequest($verify_token, string $contentType = self::contentTypes['verifyOauthRequest'][0])
    {
        list($response) = $this->verifyOauthRequestWithHttpInfo($verify_token, $contentType);
        return $response;
    }

    /**
     * Operation verifyOauthRequestWithHttpInfo
     *
     * Verify OAuth request
     *
     * @param  string $verify_token Verify token from OAuth create response (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyOauthRequest'] to see the possible values for this operation
     *
     * @throws \Platon\\ControlPanel\\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function verifyOauthRequestWithHttpInfo($verify_token, string $contentType = self::contentTypes['verifyOauthRequest'][0])
    {
        $request = $this->verifyOauthRequestRequest($verify_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation verifyOauthRequestAsync
     *
     * Verify OAuth request
     *
     * @param  string $verify_token Verify token from OAuth create response (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyOauthRequestAsync($verify_token, string $contentType = self::contentTypes['verifyOauthRequest'][0])
    {
        return $this->verifyOauthRequestAsyncWithHttpInfo($verify_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation verifyOauthRequestAsyncWithHttpInfo
     *
     * Verify OAuth request
     *
     * @param  string $verify_token Verify token from OAuth create response (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function verifyOauthRequestAsyncWithHttpInfo($verify_token, string $contentType = self::contentTypes['verifyOauthRequest'][0])
    {
        $returnType = '\Platon\\ControlPanel\\Sdk\Model\VerifyOauthRequest200Response';
        $request = $this->verifyOauthRequestRequest($verify_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'verifyOauthRequest'
     *
     * @param  string $verify_token Verify token from OAuth create response (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['verifyOauthRequest'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function verifyOauthRequestRequest($verify_token, string $contentType = self::contentTypes['verifyOauthRequest'][0])
    {

        // verify the required parameter 'verify_token' is set
        if ($verify_token === null || (is_array($verify_token) && count($verify_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $verify_token when calling verifyOauthRequest'
            );
        }


        $resourcePath = '/oauth/requests/verify';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $verify_token,
            'verify_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
