<?php
/**
 * ChangeDomainNameserversRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ChangeDomainNameserversRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ChangeDomainNameserversRequest
 * @package     Platon\\ControlPanel\\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ChangeDomainNameserversRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ChangeDomainNameserversRequest"
     */
    public function testChangeDomainNameserversRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cname"
     */
    public function testPropertyCname()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dns_servers_opt"
     */
    public function testPropertyDnsServersOpt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns"
     */
    public function testPropertyNs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns1"
     */
    public function testPropertyNs1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns1_ipv4"
     */
    public function testPropertyNs1Ipv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns1_ipv6"
     */
    public function testPropertyNs1Ipv6()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns2"
     */
    public function testPropertyNs2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns2_ipv4"
     */
    public function testPropertyNs2Ipv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns2_ipv6"
     */
    public function testPropertyNs2Ipv6()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns3"
     */
    public function testPropertyNs3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns3_ipv4"
     */
    public function testPropertyNs3Ipv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns3_ipv6"
     */
    public function testPropertyNs3Ipv6()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns4"
     */
    public function testPropertyNs4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns4_ipv4"
     */
    public function testPropertyNs4Ipv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ns4_ipv6"
     */
    public function testPropertyNs4Ipv6()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
