<?php
/**
 * CreateOauthRequest200ResponseDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateOauthRequest200ResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description CreateOauthRequest200ResponseData
 * @package     Platon\\ControlPanel\\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateOauthRequest200ResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateOauthRequest200ResponseData"
     */
    public function testCreateOauthRequest200ResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verify_token"
     */
    public function testPropertyVerifyToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verify_url"
     */
    public function testPropertyVerifyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verify_interval_seconds"
     */
    public function testPropertyVerifyIntervalSeconds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
