<?php
/**
 * MergeCartItems200ResponseDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MergeCartItems200ResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description MergeCartItems200ResponseData
 * @package     Platon\\ControlPanel\\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MergeCartItems200ResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MergeCartItems200ResponseData"
     */
    public function testMergeCartItems200ResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merged"
     */
    public function testPropertyMerged()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_cname"
     */
    public function testPropertyFromCname()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_cname"
     */
    public function testPropertyToCname()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "moved_items"
     */
    public function testPropertyMovedItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merged_items"
     */
    public function testPropertyMergedItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "items_count"
     */
    public function testPropertyItemsCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
