<?php
/**
 * CartApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Api;

use \Platon\\ControlPanel\\Sdk\Configuration;
use \Platon\\ControlPanel\\Sdk\ApiException;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CartApiTest Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CartApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkCartCoupon
     *
     * Check and apply cart coupon.
     *
     */
    public function testCheckCartCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCartItem
     *
     * Add item to cart.
     *
     */
    public function testCreateCartItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCartItem
     *
     * Remove item from cart.
     *
     */
    public function testDeleteCartItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCartBillingAddress
     *
     * Get cart billing address.
     *
     */
    public function testGetCartBillingAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCartCoupon
     *
     * Get current cart coupon.
     *
     */
    public function testGetCartCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCartTotal
     *
     * Get cart total.
     *
     */
    public function testGetCartTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCartItems
     *
     * List cart items.
     *
     */
    public function testListCartItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCartItem
     *
     * Update cart item data.
     *
     */
    public function testUpdateCartItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCartItemCount
     *
     * Update cart item count by product and domain.
     *
     */
    public function testUpdateCartItemCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
