<?php
/**
 * DNSApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Api;

use \Platon\\ControlPanel\\Sdk\Configuration;
use \Platon\\ControlPanel\\Sdk\ApiException;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DNSApiTest Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DNSApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDnsRecord
     *
     * Create DNS record.
     *
     */
    public function testCreateDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDnsRecord
     *
     * Delete DNS record.
     *
     */
    public function testDeleteDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDnsRecords
     *
     * Get DNS records by domain.
     *
     */
    public function testGetDnsRecords()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDnsRecord
     *
     * Update DNS record.
     *
     */
    public function testUpdateDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
