<?php
/**
 * DomainApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Platon OpenAPI Engine
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Platon\\ControlPanel\\Sdk\Test\Api;

use \Platon\\ControlPanel\\Sdk\Configuration;
use \Platon\\ControlPanel\\Sdk\ApiException;
use \Platon\\ControlPanel\\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DomainApiTest Class Doc Comment
 *
 * @category Class
 * @package  Platon\\ControlPanel\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeDomainNameservers
     *
     * Change domain nameservers.
     *
     */
    public function testChangeDomainNameservers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for closeDomain
     *
     * Close external customer domain product.
     *
     */
    public function testCloseDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDomainInfo
     *
     * Get domain information and availability.
     *
     */
    public function testGetDomainInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDomains
     *
     * List customer domains.
     *
     */
    public function testListDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for registerDomain
     *
     * Register domain.
     *
     */
    public function testRegisterDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renewDomain
     *
     * Renew domain.
     *
     */
    public function testRenewDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
